### ISSUE TITLE
high latency

### ISSUE THREAD

**Issue by sriram-dsl** [openvinotoolkit/model_server#2721]
# Latency in OpenVINO Model Server Inside Kubernetes Cluster

## To Reproduce
**Steps to reproduce the behavior:**
1. **Prepare Models Repository**: Followed standard procedures to set up the models repository.
2. **OVMS Launch Command**: 
   ```bash
   docker run -d --rm \
     -v /home/raa/model:/models \
     -p 900:9000 \
     -p 800:8000 \
     openvino/model_server:latest \
     --model_path /models/model1/1 \
     --model_name model1 \
     --port 9000 \
     --rest_port 8000 \
     --log_level DEBUG
3. **Client command ** : 
      ```
       server address = 192.168.1.10:900
       client = make_grpc_client(server_address)
       pred = client.predict(inputs=inputs, model_name=model1)
      ```

# Environment
I am using OpenVINO server for model deployment on edge devices with an **Intel i7-13th Gen** processor. My PyTorch model is trained with an image size of **640**.

- **Standalone Inference**: The prediction time for PyTorch weights is consistently **<0.01 seconds** per image.
- **IR Converted Weights**: Similar inference time in standalone mode.
- **In Kubernetes Cluster**: When deployed, the OpenVINO server takes approximately **1.5 seconds** per prediction using gRPC calls.
- **Observation**: Running the OpenVINO server outside the cluster in a container yields **<0.01 seconds** inference time for IR converted weights, while the same server inside the cluster significantly increases latency.

# Expected Behavior
I expected the inference time for the OpenVINO Model Server inside the Kubernetes cluster to be comparable to that observed outside the cluster (i.e., **<0.01 seconds**).

# model directory format 
```
model/
├── model1/
│   └── 1/
│       ├── model.bin
│       ├── model.mapping
│       └── model.xml

```

**Comment by mzegla** [comment]
Could you share Kubernetes deployment configuration? I can see you are running with DEBUG log level - can you share logs from the server in your deployment with a few predictions logged?

**Comment by mzegla** [comment]
Okay, from the logs it looks like prediction takes  ~1.4 s. Are you sure there are no resource constrains for your deployment? 
If standalone server and K8S deployment run on the same machine then it looks like server running in kubernetes cluster is using a fraction on resources available to standalone instance.

**Comment by sriram-dsl** [comment]
I have been using this OpenVINO server for the last two years without any issues. However, we started encountering this problem in the most recent deployments, even though we are using the same resources as in previous deployments.

this is the resource column for the deployment :
```
  # Resource Configuration
  metaResources:
      resources:
        limits:
          cpu: "1"                     # Low resource limits for CPU
          memory: "2G"                 # Low resource limits for memory
        requests:
          cpu: "1"                     # Low resource requests for CPU
          memory: "2G"                 # Low resource requests for memory

  serviceName: inference-service1     # Name of the inference service
  serviceType: ClusterIP              # Service type for the inference service
  port: 9000                          # Port for the inference service
  grpcWorkers: 2                      # Number of gRPC workers
  labels:
    app: inference1                   # Labels for identifying the application

```
